/*
 * Copyright (c) 2005, 2014, EVECOM Technology Co.,Ltd. All rights reserved.
 * EVECOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 * 
 */
package net.evecom.android.bean;

/**
 * 数据字典表 SysBaseDict generated by MyEclipse Persistence Tools
 * 
 * @version 2.1
 * @author Mars zhang
 */

public class SysBaseDict implements java.io.Serializable {

    /**
     * 数据字典主键
     */
    private String sbdId;

    /**
     * 数据字典代码
     */
    private String sbdCode;

    /**
     * 数据字典名称
     */
    private String sbdName;

    /**
     * 数据字典类别
     */
    private String sbdType;

    /**
     * 数据字典备注
     */
    private String sbdDesc;

    /**
     * 数据字典父主键
     */
    private String sbdPid;
    /**
     * 数据字典父主键
     */
    private Integer orderNO;

    // Constructors

    /** default constructor */
    public SysBaseDict() {
    }

    /** full constructor */
    public SysBaseDict(String sbdCode, String sbdName, String sbdType, String sbdDesc, String sbdPid) {
        this.sbdCode = sbdCode;
        this.sbdName = sbdName;
        this.sbdType = sbdType;
        this.sbdDesc = sbdDesc;
        this.sbdPid = sbdPid;
    }

    // Property accessors

    public String getSbdId() {
        return this.sbdId;
    }

    public void setSbdId(String sbdId) {
        this.sbdId = sbdId;
    }

    public String getSbdCode() {
        return this.sbdCode;
    }

    public void setSbdCode(String sbdCode) {
        this.sbdCode = sbdCode;
    }

    public String getSbdName() {
        return this.sbdName;
    }

    public void setSbdName(String sbdName) {
        this.sbdName = sbdName;
    }

    public String getSbdType() {
        return this.sbdType;
    }

    public void setSbdType(String sbdType) {
        this.sbdType = sbdType;
    }

    public String getSbdDesc() {
        return this.sbdDesc;
    }

    public void setSbdDesc(String sbdDesc) {
        this.sbdDesc = sbdDesc;
    }

    public String getSbdPid() {
        return this.sbdPid;
    }

    public void setSbdPid(String sbdPid) {
        this.sbdPid = sbdPid;
    }

    public Integer getOrderNO() {
        return orderNO;
    }

    public void setOrderNO(Integer orderNO) {
        this.orderNO = orderNO;
    }

}